services:
  - type: web
    name: coffee-shop
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn coffee_shop.wsgi
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: coffee_shop_db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: .onrender.com

databases:
  - name: coffee_shop_db
    provider: postgres
    plan: free
